language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=5
    # storepass
    - secure: "cRdupUus7UsluRI62V2nmfXZaWM90aL657EBM+KH20FlHMR5KQc0ILN+2dGYygRS2sydI9n2tPPnmzWFKGIw6KrbzsAFNJDFubyLnBv0+Gpt5AXVmvXH/RFcnfcdrm4jyNhcuwpGqJrgaG9mUpDioT4zQlTtCAtQUgXyk4m40Q3dSSaxP7w5VtKIZE6wFtInqP0eUhwaW1srjaDZ7WVDdJsvKM7ou65oCEK5bRXLHwqSWKxrJx+iJ07KTFtdS1vYmM9MTLsiGtorLixH0QixmsRo/cDP0QO4n98w5cc7aKUSGtSLlKKxiRS6gsh1QWIjo/YtABIgyxgu6BGYIeYKbjizVrmfGJZyZ2aDJx3PBVvbd5sQmqRIccEZBR9G5K4UrM+f2Hweo5PsXATRBdKwrEi6dJmzh4hwKNpYCpyyi0eSJNgN1STHazVE3RRnFoNciGROCcECQauZ2vZigfAKlOZdQqmKtUgXV2yTU//b79NoVkiRKeVx5kpGcxwHhtBGY1GP6QfPj8C64I0RDuZKEpDq964dgjFUDxIfj9Hdep1123VxcHgddKDjpH6T3IoRFEvsMiWhayv90RACe2VKPOa2wD9YbjWkrISKUQh9Ru26sBn5OzkypNdmClKkRbLZk5CNlNub6q+uIOa/yxy8hf2+MxXrQ/uf6QqKDQdT9Vs="

android:
  components:
    - tools
    - platform-tools
    - tools
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_d4f65c79752c_key -iv $encrypted_d4f65c79752c_iv -in android-keys.jks.enc -out android-keys.jks -d
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-24"
  - yes | sdkmanager "build-tools;27.0.3"
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - ./gradlew --no-daemon clean build

before_deploy:
  - |
    apks=($(find "$TRAVIS_BUILD_DIR" -name '*release*.apk'))
    for apk in "${apks[@]}"; do
      signedFile="$TRAVIS_BUILD_DIR/$(basename "$apk" | sed 's/unsigned/signed/')"
      jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $TRAVIS_BUILD_DIR/android-keys.jks -storepass $storepass "$apk" atvlaunchers
      jarsigner -verify "$apk"
      ${ANDROID_HOME}/build-tools/27.0.3/zipalign -v 4 "$apk" "$signedFile"
    done
  - pwd && ls -la

deploy:
  provider: releases
  file: "*-signed.apk"
  file_glob: true
  skip_cleanup: true
  draft: true
  on:
    repo: hoshsadiq/bravia-youview-player-launchers
    jdk: oraclejdk8
  api_key:
    secure: "B7fy0NFd/S3TN97X71K0xUu5taCe7rMKrStsSs1pD06tfKVf0pJCAkhqTI4NQf5bV9/Dc7jR6Gg+EQAyfLZCjxy2pGSyR6Ju4iPN2iLVu+aklwOYuI6APCIJzptxkCPoG91TEbMpNCBTn2LfeQ0+iccX/KDH+/4J1y/hiT/keOEAipiz96jDUTneaWK43eZrqeacwRyKxnP1/vknDn7o9mrcm469q/cv75RCoEAon2DLodAktFfEMiEM4yPTrtt7Znv1iYLy1gBXtVHW4gULHrP3h6TqwbPjWvuPSkThgVwCJXNGyrK1GJrncTFK/tWi/PXIiQ2kn7BnqL7OzXB/ofOA4rZzhMrLYXUJgr7JkWB9FiTVVltn3CrASW5PR1D9rmdlI7H+rovD10HFHBD+N+CENLq50hdWhyO3a2CKZztJe8aIhAJUuMGR5r9QXSSPAIPi2m+fW1TLzzsQ+F16pCSoz+3tZpfJT8EEHuSoNA0ZYl7ojlgwbXYYTnZmlXTC82t8tZkeZQh+khrG/I0117FqgyLzuoHtpyneelBjX8EcR9k7EUVf2KZsEZKxnMX8i8/XtlXeRU4CVgy3HSSBJ0fFMxRoysjxc/JC6r7VZP9lBYUpTfpRN3lDn3mdMHpCvZZuLrBa+ROmbuJebs5qIMtaDus8bhV5lpjlQFio+fM="
